-- ============================================================
-- KABEQ (卡贝奇) 2025 New Products — Opportunity Radar Seed Data
-- Generated from: 卡贝奇新品报价单V2.1.pdf
-- Factory: KABEQ — Crafting High-End Aesthetic Furniture for Young People
-- Batch ID: 2026-03-KABEQ
-- ============================================================

-- ── Step 1: Insert KABEQ factory ────────────────────────────────────────────
INSERT IGNORE INTO `factories`
  (`id`, `name`, `description`, `country`, `city`, `certifications`,
   `established`, `employeeCount`, `verified`, `rating`, `reviewCount`,
   `coverImage`, `createdAt`, `updatedAt`)
VALUES
  (100, 'KABEQ (卡贝奇)',
   'Crafting High-End Aesthetic Furniture for Young People. Specializing in sofas, armchairs, dining tables, and coffee tables with modern and Japandi-inspired designs.',
   'China', 'Foshan',
   '["ISO 9001","CE","BSCI"]',
   2015, 500, 1, 4.7, 128,
   'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
   NOW(), NOW());

-- ── Step 2: Insert products ──────────────────────────────────────────────────
INSERT IGNORE INTO `products`
  (`id`, `factoryId`, `name`, `description`, `category`, `moq`, `leadTime`,
   `price`, `currency`, `status`, `coverImage`, `tags`, `createdAt`, `updatedAt`)
VALUES
  (200, 100, 'Rock Sofa — 岩石沙发', 'Modular rock-inspired design, highly configurable layouts Material: C-grade fabric. Size: Multiple configurations, 2-4 seat, modular.', 'Sofas', 1, 30, 277.78, 'USD', 'active', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600', '["modular", "minimalist", "fabric", "sofas"]', NOW(), NOW()),
  (201, 100, 'Serpentine Sofa — 蛇形沙发', 'Iconic curved serpentine design, premium leather, statement living room piece Material: C-grade half leather / full leather. Size: φ4600mm curved serpentine configuration.', 'Sofas', 1, 30, 3501.39, 'USD', 'active', 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600', '["luxury", "curved", "statement piece", "leather", "sofas"]', NOW(), NOW()),
  (202, 100, 'Dylan Sofa — 迪兰沙发', 'Clean lines, premium leather, versatile sizing for modern living rooms Material: C-grade half leather / full leather. Size: 2-4 seat, L-shape available, 2390-4990mm width.', 'Sofas', 1, 30, 1152.78, 'USD', 'active', 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=600', '["modern", "leather", "sectional", "sofas"]', NOW(), NOW()),
  (203, 100, 'Lawrence Sofa — 劳伦斯沙发', 'Multi-material options, generous sizing, contemporary European aesthetic Material: C-grade fabric / half leather / full leather. Size: 2-4 seat, L-shape, 2800-5200mm.', 'Sofas', 1, 30, 1479.17, 'USD', 'active', 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600', '["contemporary", "multi-material", "sectional", "sofas"]', NOW(), NOW()),
  (204, 100, 'Cloud Sofa — 云沙发', 'Viral \'cloud sofa\' trend, ultra-soft boucle-style fabric, TikTok-friendly aesthetic Material: C-grade fabric. Size: 2-4 seat, modular cloud shape.', 'Sofas', 1, 30, 1334.72, 'USD', 'active', 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=600', '["cloud", "fluffy", "cozy", "fabric", "viral", "sofas"]', NOW(), NOW()),
  (205, 100, 'Pixel Sofa — 像素沙发', 'Unique pixel/block modular system, fully customizable configuration, design-forward Material: C-grade full leather / half leather. Size: Modular pixel blocks, 35-40cm per module.', 'Sofas', 1, 30, 377.78, 'USD', 'active', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600', '["modular", "geometric", "customizable", "designer", "sofas"]', NOW(), NOW()),
  (206, 100, 'Sandbag Sofa — 沙包沙发', 'Relaxed sandbag aesthetic, casual living, affordable entry point Material: C-grade fabric. Size: 2-3 seat, 2800-3350mm.', 'Sofas', 1, 30, 1106.94, 'USD', 'active', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600', '["casual", "relaxed", "fabric", "affordable", "sofas"]', NOW(), NOW()),
  (207, 100, 'Cloud Puff Sofa — 云朵沙发', 'Puffy cloud aesthetic, Instagram-worthy, affordable price point, high viral potential Material: C-grade half leather / fabric. Size: 1-3 seat, 1370-3260mm.', 'Sofas', 1, 30, 520.83, 'USD', 'active', 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=600', '["cloud", "puffy", "cozy", "Instagram", "viral", "sofas"]', NOW(), NOW()),
  (208, 100, 'Elephant Ear Sofa — 大象耳朵沙发', 'Distinctive organic silhouette, conversation starter, unique market positioning Material: C-grade half leather / fabric. Size: 2-3 seat, 2100-3000mm.', 'Sofas', 1, 30, 737.5, 'USD', 'active', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600', '["organic", "sculptural", "unique silhouette", "sofas"]', NOW(), NOW()),
  (209, 100, 'Budapest Sofa — 布达佩斯沙发', 'Classic European styling, neutral tones, broad market appeal Material: C-grade fabric. Size: 2-4 seat, 2800-3600mm.', 'Sofas', 1, 30, 1011.11, 'USD', 'active', 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600', '["European", "classic", "fabric", "neutral", "sofas"]', NOW(), NOW()),
  (210, 100, 'Marshmallow Sofa — 棉花糖沙发', 'Ultra-soft marshmallow texture, Japandi-friendly, includes ottoman option Material: C-grade half leather / fabric. Size: Ottoman + 2-3 seat, 2140-3220mm.', 'Sofas', 1, 30, 240.28, 'USD', 'active', 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=600', '["soft", "cozy", "marshmallow", "Japandi", "sofas"]', NOW(), NOW()),
  (211, 100, 'Brown Sugar Sofa — 黑糖沙发', 'Affordable leather sofa, clean modern lines, strong value proposition Material: C-grade half leather / full leather. Size: 2-4 seat, 2400-3000mm.', 'Sofas', 1, 30, 965.28, 'USD', 'active', 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600', '["leather", "modern", "affordable", "bestseller", "sofas"]', NOW(), NOW()),
  (212, 100, 'Cloud Sofa ZY — 云朵沙发 ZY', 'Premium cloud sofa with leather option, strong 2025 trend alignment Material: C-grade half leather / full leather / fabric. Size: 3-seat, 2700mm, multi-material.', 'Sofas', 1, 30, 955.56, 'USD', 'active', 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=600', '["cloud", "multi-material", "premium", "sofas"]', NOW(), NOW()),
  (213, 100, 'Moon Sofa — 月亮沙发', 'Moon-inspired curved design, cozy fabric, growing curved furniture trend Material: C-grade fabric. Size: 2-4 seat, L-shape, 2800-4640mm.', 'Sofas', 1, 30, 1061.11, 'USD', 'active', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600', '["moon", "curved", "fabric", "cozy", "sofas"]', NOW(), NOW()),
  (214, 100, 'Caterpillar Lounge Chair — 毛毛虫休闲椅', 'Togo-style floor lounge chair, viral on social media, Japandi aesthetic, low MOQ Material: Fabric. Size: 880*1020*700mm + optional ottoman.', 'Armchairs', 1, 30, 240.28, 'USD', 'active', 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600', '["floor chair", "lounge", "Japandi", "viral", "togo-style", "armchairs"]', NOW(), NOW()),
  (215, 100, 'Crab Chair — 螃蟹椅', 'Sculptural designer chair, unique crab-inspired form, strong social media appeal Material: Fabric. Size: 820*760*690mm.', 'Armchairs', 1, 30, 468.06, 'USD', 'active', 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600', '["designer", "sculptural", "statement", "unique", "armchairs"]', NOW(), NOW()),
  (216, 100, 'Hippo Chair — 小河马椅', 'Adorable round form, boucle-style fabric, perfect for cozy reading corners Material: Fabric. Size: 800*790*720mm.', 'Armchairs', 1, 30, 277.78, 'USD', 'active', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600', '["cute", "round", "boucle", "cozy", "Japandi", "armchairs"]', NOW(), NOW()),
  (217, 100, 'Mother\'s Embrace Chair — 妈妈的怀抱', 'Oversized cocoon design, immersive comfort, strong gifting/nursery appeal Material: Fabric. Size: 1200*1170*980mm.', 'Armchairs', 1, 30, 450.0, 'USD', 'active', 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=600', '["oversized", "cocoon", "cozy", "unique", "armchairs"]', NOW(), NOW()),
  (218, 100, 'Polar Bear Ottoman — 趴趴熊', 'Polar bear shaped ottoman, novelty gift item, kids room or playful living space Material: Fabric. Size: 940*550*340mm.', 'Armchairs', 1, 30, 175.0, 'USD', 'active', 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600', '["novelty", "kids", "cute", "ottoman", "gift", "armchairs"]', NOW(), NOW()),
  (219, 100, 'Embrace Loveseat — 相拥休闲沙发', 'Bold red loveseat, romantic statement piece, Valentine\'s/anniversary gift potential Material: Fabric. Size: 2000*870*740mm.', 'Armchairs', 1, 30, 468.06, 'USD', 'active', 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600', '["loveseat", "red", "bold", "statement", "romantic", "armchairs"]', NOW(), NOW()),
  (220, 100, 'Yoko Dining Chair — Yoko 餐椅', 'Sleek leather dining chair, modern silhouette, strong set-selling potential Material: Half leather / full leather. Size: 620*580*810mm.', 'Dining Chairs', 4, 30, 219.44, 'USD', 'active', 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600', '["dining", "leather", "modern", "set", "dining chairs"]', NOW(), NOW()),
  (221, 100, 'Dining Chair KA-020 — 餐椅 KA-020', 'Ultra-affordable dining chair, high volume potential, minimalist design Material: Tech fabric. Size: 480*600*820mm.', 'Dining Chairs', 4, 30, 76.39, 'USD', 'active', 'https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=600', '["affordable", "dining", "minimalist", "volume", "dining chairs"]', NOW(), NOW()),
  (222, 100, 'Sintered Stone Dining Table KT-001 — 岩板餐桌 KT-001', 'Affordable sintered stone dining table, modern industrial frame, strong value Material: Sintered stone top, carbon steel frame. Size: 1400*800*730mm.', 'Dining Tables', 1, 30, 234.72, 'USD', 'active', 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=600', '["sintered stone", "modern", "dining", "affordable", "dining tables"]', NOW(), NOW()),
  (223, 100, 'Round Sintered Stone Dining Table — 圆形岩板餐桌 KT-005', 'Round marble/sintered stone table, luxury aesthetic, premium material options Material: Sintered stone / marble top, brushed black titanium steel. Size: φ1350*750mm round.', 'Dining Tables', 1, 30, 508.33, 'USD', 'active', 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=600', '["round", "marble", "sintered stone", "premium", "luxury", "dining tables"]', NOW(), NOW()),
  (224, 100, 'Stone Top Wood Base Dining Table — 岩板木脚餐桌 KT-006', 'Japandi stone-top wood-leg combo, top trending aesthetic for 2025-2026 Material: Sintered stone / marble top, black oak wood legs. Size: 1600-1800mm length.', 'Dining Tables', 1, 30, 409.72, 'USD', 'active', 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600', '["Japandi", "wood", "stone", "natural", "trending", "dining tables"]', NOW(), NOW()),
  (225, 100, 'Sintered Stone Coffee Table KC-004 — 岩板茶几 KC-004', 'Sintered stone coffee table, modern industrial aesthetic, competitive price Material: Sintered stone top, carbon steel base. Size: 1350*640*400mm.', 'Coffee Tables', 1, 30, 284.72, 'USD', 'active', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600', '["sintered stone", "modern", "coffee table", "affordable", "coffee tables"]', NOW(), NOW()),
  (226, 100, 'Glass & Marble Coffee Table KC-006 — 玻璃大理石茶几 KC-006', 'Natural Hanbayu marble + glass combo, luxury living room centerpiece Material: Glass + natural marble (Han Bai Yu). Size: 1000*700*400mm.', 'Coffee Tables', 1, 30, 515.28, 'USD', 'active', 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=600', '["marble", "glass", "luxury", "premium", "natural stone", "coffee tables"]', NOW(), NOW()),
  (227, 100, 'Round Sintered Stone Side Table — 岩板圆形茶几 KC-010', 'Affordable round side table, two sizes, Japandi-friendly, high volume potential Material: Sintered stone top, black painted wood legs. Size: φ500-1000mm, two sizes.', 'Coffee Tables', 1, 30, 131.94, 'USD', 'active', 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600', '["round", "side table", "affordable", "Japandi", "versatile", "coffee tables"]', NOW(), NOW());

-- ── Step 3: Insert radar batch ─────────────────────────────────────────────
INSERT IGNORE INTO `radar_batches`
  (`id`, `niche`, `productCount`, `factoryCount`, `summary`, `isPublished`, `publishedAt`, `createdAt`)
VALUES
  ('2026-03-KABEQ', 'furniture',
   28, 1,
   'New batch from KABEQ (卡贝奇): 2025 new product line featuring cloud sofas, modular pixel sofas, sintered stone dining tables, and designer armchairs. Strong Japandi and TikTok-friendly aesthetics.',
   1, NOW(), NOW());

-- ── Step 4: Insert opportunity analysis ─────────────────────────────────────
INSERT IGNORE INTO `product_opportunity_analysis`
  (`productId`, `niche`, `opportunityScore`, `trendScore`, `marginScore`,
   `competitionScore`, `demandScore`, `headline`, `whyNow`, `targetAudience`,
   `suggestedPlatforms`, `actionSteps`, `risks`, `estimatedMargin`,
   `suggestedRetailPrice`, `keywords`, `tags`, `batchId`, `isActive`,
   `createdAt`, `updatedAt`)
VALUES
  (200, 'furniture',
   78, 82, 65,
   60, 75,
   'Modular Rock-Inspired Sofa: The Minimalist Must-Have for Young Homes',
   'In 2025-2026, modular and minimalist furniture styles dominate the US/EU markets, especially among young urban consumers seeking flexible, aesthetic living solutions. The Rock Sofa’s unique design taps into the growing demand for customizable, Instagrammable furniture that blends Japandi and cloud style influences. Additionally, TikTok Shop’s surge as a furniture sales channel makes this an ideal time to launch.',
   'Urban professionals aged 25-40, mid to upper-middle income ($50K-$90K/year), design-conscious renters or first-time homeowners who prioritize modular, minimalist, and Instagram-worthy furniture to complement their compact living spaces and social media lifestyle.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Source a sample unit from KABEQ to verify quality and shipping logistics with a 3PL partner.", "Run targeted TikTok and Instagram ads focusing on modular living and minimalist aesthetics to validate demand.", "Leverage influencer partnerships and user-generated content to build social proof and brand awareness.", "Expand product line with complementary modular pieces and optimize logistics for faster delivery and reduced freight costs."]',
   'High shipping costs and potential delays could impact customer satisfaction; the C-grade fabric may limit appeal in premium segments. Competition from established modular sofa brands remains moderate but growing.',
   '45-65%',
   '$799-$1,499',
   '["modular sofa", "minimalist furniture", "rock inspired sofa", "fabric sectional", "configurable couch"]',
   '["modular", "minimalist", "fabric", "young professionals"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (201, 'furniture',
   68, 55, 60,
   75, 50,
   'Luxury Curved Serpentine Sofa: Statement Leather Piece for Trendy Homes',
   'The luxury curved leather sofa taps into the growing demand for unique, statement furniture among young affluent buyers seeking premium aesthetics. Despite high shipping costs, dropshipping this iconic design with 3PL solutions can capture niche buyers craving standout living room pieces in 2025-2026.',
   'Affluent urban professionals aged 30-45, income $90K+, design-conscious, valuing luxury statement furniture that reflects status and modern lifestyle.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Establish a reliable freight-forwarding and 3PL partnership to manage shipping costs and logistics.", "Validate demand with targeted ads on TikTok and Instagram focusing on luxury home decor enthusiasts.", "Leverage influencer marketing and lifestyle content showcasing the sofa as a centerpiece in modern living spaces.", "Expand product line with complementary luxury furniture pieces and optimize for Wayfair and Amazon listings."]',
   'High shipping and return costs may deter some buyers; niche luxury market limits volume. Market trends favor modular and Japandi styles over heavy leather luxury pieces.',
   '40-55%',
   '$7500-$9500',
   '["luxury sofa", "curved leather sofa", "statement furniture", "serpentine sofa", "premium living room"]',
   '["luxury", "leather", "curved", "statement_piece"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (202, 'furniture',
   72, 68, 60,
   55, 70,
   'Modern Leather Sectionals for Stylish Young Urban Living Rooms',
   'With rising urbanization and remote work, young professionals seek premium, versatile sofas that fit modern living spaces. The Dylan Sofa’s clean lines and leather appeal to the growing demand for stylish yet functional furniture in 2025-2026. Leveraging emerging TikTok Shop trends and 3PL solutions can overcome traditional shipping hurdles.',
   'Affluent urban professionals aged 28-38, earning $60K-$120K annually, valuing modern aesthetics, quality materials, and flexible living room layouts in apartments or condos.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Establish partnerships with 3PL and freight forwarders to optimize shipping costs and delivery times.", "Run targeted TikTok Shop campaigns showcasing the sofa\\u2019s modern design and modular options to validate demand.", "Leverage influencer marketing and lifestyle content emphasizing premium leather and versatile sizing.", "Scale by expanding product variations (colors, sizes) and cross-listing on Wayfair and Amazon for broader reach."]',
   'High shipping costs and potential delays can impact customer satisfaction; leather sofas face stiff competition from established brands and local retailers.',
   '40-55%',
   '$2200-$4500',
   '["modern leather sofa", "sectional sofa", "L-shape sofa", "premium leather couch", "urban living room furniture"]',
   '["modern", "leather", "sectional", "versatile", "premium"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (203, 'furniture',
   72, 78, 65,
   55, 70,
   'Contemporary Multi-Material Lawrence Sofa: Big Style, Big Impact!',
   'Young urban professionals in the US and EU are prioritizing stylish, modular sofas that blend materials and offer generous sizing for multifunctional living spaces. The Lawrence Sofa’s contemporary European aesthetic and flexible material options align perfectly with 2025-2026 trends, while the low MOQ enables agile dropshipping entry.',
   'Affluent millennials and Gen Z (ages 28-38), earning $60K-$120K annually, living in urban apartments or modern homes, valuing design-forward, multifunctional furniture that complements their minimalist yet cozy lifestyle.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Establish a partnership with KABEQ and negotiate freight-forwarding logistics to optimize shipping costs.", "Run targeted ads on TikTok and Instagram focusing on young professionals seeking modular, stylish sofas.", "Leverage influencer collaborations showcasing the sofa\\u2019s multi-material and sectional versatility in real living spaces.", "Expand product line with complementary pieces and bundle offers, scaling via Wayfair and Amazon for broader reach."]',
   'High shipping costs and potential delays could impact customer satisfaction; competition from established European and US brands remains moderate but growing.',
   '45-60%',
   '$2999-$4999',
   '["modular sofa", "sectional couch", "contemporary sofa", "multi-material furniture", "European style sofa"]',
   '["contemporary", "sectional", "multi-material", "modular"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (204, 'furniture',
   78, 85, 60,
   65, 75,
   'Capitalize on the viral Cloud Sofa trend with cozy, modular luxury!',
   'The Cloud Sofa taps into the booming TikTok-driven furniture trend for ultra-soft, cozy, and modular designs favored by young urban buyers. With growing demand for aesthetic, Instagrammable home pieces in 2025-2026, this product aligns perfectly with current Japandi and cloud style preferences. Low MOQ and a fresh factory line make it ideal for early movers in dropshipping.',
   'Young professionals aged 25-35, urban renters or new homeowners, $50K-$90K annual income, lifestyle focused on trendy, cozy, and Instagrammable home decor with a preference for modular and viral furniture pieces.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Source a sample Cloud Sofa to evaluate quality and shipping logistics via freight forwarder.", "Test demand with targeted TikTok Shop ads and Shopify pre-launch landing pages.", "Leverage influencer partnerships and viral TikTok content showcasing the sofa\\u2019s cozy, modular appeal.", "Expand to Amazon and Wayfair with optimized listings and bundle offers to scale sales."]',
   'High shipping costs and potential delays could impact margins and customer satisfaction; competition may increase as the trend matures.',
   '45-60%',
   '$2999-$3999',
   '["cloud sofa", "modular sofa", "boucle sofa", "cozy furniture", "TikTok furniture"]',
   '["cloud", "modular", "cozy", "boucle", "viral"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (205, 'furniture',
   78, 85, 65,
   70, 75,
   'Modular Pixel Sofa: The Future of Customizable Designer Seating!',
   'The Pixel Sofa taps into the booming modular and geometric furniture trend favored by young urban consumers seeking personalized, design-forward pieces. With TikTok Shop fueling furniture discovery and sales in 2025-2026, this unique customizable sofa offers a fresh alternative to traditional bulky sofas, fitting perfectly into smaller, style-conscious living spaces.',
   'Young professionals and creatives aged 25-40, earning $50K-$120K annually, living in urban apartments or modern homes, valuing aesthetics, customization, and social media trends in home decor.',
   '["shopify", "tiktok_shop", "amazon", "etsy", "wayfair"]',
   '["Source sample units from KABEQ to evaluate build quality and shipping logistics", "Run targeted TikTok and Instagram ads to validate consumer interest and price sensitivity", "Leverage influencer partnerships and user-generated content to showcase modular configurations", "Expand SKUs with varied leather grades and module sizes, optimize 3PL partnerships for faster delivery"]',
   'High shipping costs and potential delays could impact customer satisfaction; premium price points may limit mass appeal without strong brand storytelling.',
   '45-65%',
   '$899-$2499',
   '["modular sofa", "customizable furniture", "designer sofa", "pixel sofa", "geometric sofa"]',
   '["modular", "customizable", "designer", "leather", "modern"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (206, 'furniture',
   65, 55, 50,
   60, 60,
   'Casual Sandbag Sofa taps relaxed vibes for young urban homes',
   'The Sandbag Sofa offers an affordable, casual aesthetic that resonates with young buyers seeking comfort and style without premium pricing. While not a top trend like Japandi or modular, its relaxed fabric look fits growing demand for cozy, lived-in furniture. Dropshipping is viable now due to improved 3PL and freight options reducing shipping friction for bulky items.',
   'Urban professionals aged 25-40, mid-level income ($50k-$90k), valuing casual comfort and affordable style for first apartments or shared living spaces, often renting and influenced by social media trends.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Negotiate freight-forwarding and 3PL partnerships to optimize shipping costs", "Test product demand with targeted TikTok Shop ads focused on young renters", "Leverage casual lifestyle content highlighting relaxed, cozy living spaces", "Expand to Wayfair and Amazon with optimized listings and customer reviews"]',
   'High shipping costs and delivery times could deter buyers; mid-tier fabric quality may not satisfy premium buyers, limiting upsell potential.',
   '40-55%',
   '$1800-$2200',
   '["casual sofa", "fabric couch", "relaxed living room", "affordable sofa", "urban furniture"]',
   '["casual", "fabric", "affordable", "relaxed"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (207, 'furniture',
   78, 85, 70,
   65, 80,
   'Cloud Puff Sofa: Viral, Cozy, and Perfect for Young Trendsetters!',
   'The Cloud Puff Sofa taps into the booming cloud and puffy furniture trend dominating TikTok and Instagram in 2025-2026. Young urban consumers crave Instagrammable, cozy pieces that blend style and comfort, making this an ideal moment to introduce a viral, affordable sofa with flexible sizing. The low MOQ and factory pricing enable competitive dropshipping margins despite shipping challenges.',
   'Urban millennials and Gen Z (ages 25-40), middle to upper-middle income ($50K-$90K/year), design-conscious renters or first-time homeowners who prioritize Instagram-worthy, cozy, and affordable furniture to elevate their living spaces.',
   '["shopify", "tiktok_shop", "amazon", "etsy", "wayfair"]',
   '["Source samples to verify quality and shipping logistics with 3PL or freight forwarders.", "Test market demand via TikTok Shop ads and Instagram influencer partnerships targeting young urban buyers.", "Create viral content showcasing the sofa\\u2019s cloud aesthetic and cozy appeal, leveraging UGC and TikTok trends.", "Scale by expanding SKUs (1-3 seat options), bundling with complementary decor, and optimizing shipping to reduce costs."]',
   'High shipping costs and potential damage during transit could impact margins and customer satisfaction; competition may increase as cloud-style furniture gains popularity.',
   '45-65%',
   '$999-$1799',
   '["cloud sofa", "puffy sofa", "Instagram furniture", "cozy living room", "trendy sofa"]',
   '["cloud", "puffy", "cozy", "Instagram", "viral"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (208, 'furniture',
   72, 65, 60,
   75, 70,
   'Sculptural Elephant Ear Sofa: Stand Out with Organic Luxury Seating',
   'In 2025-2026, young urban buyers crave unique, sculptural furniture that doubles as art, making the Elephant Ear Sofa a fresh conversation piece. With TikTok Shop fueling demand for aesthetic home decor and a growing appetite for organic silhouettes beyond Japandi and cloud styles, this sofa taps into emerging niche trends. The low MOQ and factory pricing enable competitive entry despite high shipping costs.',
   'Affluent urban professionals aged 28-38, earning $70K+, design-conscious, valuing statement pieces that blend comfort with artful aesthetics, often renting or owning modern apartments in US/EU metro areas.',
   '["shopify", "tiktok_shop", "amazon", "etsy", "wayfair"]',
   '["Contact KABEQ for detailed shipping and customization options to optimize cost.", "Run targeted TikTok Shop ads showcasing the sofa\\u2019s unique silhouette and organic design.", "Leverage influencer partnerships in home decor and interior design niches to build social proof.", "Expand into Wayfair and Amazon with bundled offers and seasonal promotions to scale."]',
   'High shipping and return costs could erode margins; niche style may limit mass appeal beyond design-savvy buyers.',
   '45-60%',
   '$1,499 - $2,299',
   '["organic sofa", "sculptural furniture", "unique silhouette sofa", "modern statement sofa", "designer couch"]',
   '["organic", "sculptural", "unique silhouette", "high-end aesthetic", "young professionals"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (209, 'furniture',
   68, 55, 50,
   60, 65,
   'Classic European Fabric Sofa Meets Young Buyers’ Taste in 2025',
   'As young professionals seek timeless yet neutral-toned furniture, the Budapest Sofa’s classic European design fits well with broad aesthetic preferences. Despite rising interest in modular and Japandi styles, there remains steady demand for classic, fabric sofas with neutral palettes, especially in urban US/EU markets. Dropshipping this product now leverages growing TikTok Shop furniture sales and the factory’s low MOQ.',
   'Urban professionals aged 28-38, $50K-$90K annual income, style-conscious renters or first-time homeowners valuing classic European aesthetics and neutral tones for versatile living spaces.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Negotiate freight-forwarding and 3PL options to optimize shipping costs and delivery times.", "Test market demand via TikTok Shop ads targeting young urban professionals with interest in classic and neutral furniture.", "Leverage influencer marketing focusing on European classic interior themes and neutral fabric sofas.", "Expand to Wayfair and Amazon with optimized listings and bundle offers to scale volume and reduce per-unit shipping costs."]',
   'High shipping costs and delivery times can deter buyers; fabric quality (C-grade) may lead to returns or dissatisfaction if not clearly communicated.',
   '40-55%',
   '$1999-$2499',
   '["classic European sofa", "neutral fabric sofa", "fabric couch", "2-4 seat sofa", "urban living room furniture"]',
   '["classic", "fabric", "neutral", "European", "sofa"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (210, 'furniture',
   78, 85, 65,
   70, 80,
   'Ultra-soft Japandi Marshmallow Sofa taps booming cozy decor trend!',
   'In 2025-2026, the Japandi aesthetic combined with ultra-soft, cozy furniture is surging among young urban buyers seeking comfort and minimalist style. The Marshmallow Sofa’s unique texture and modular ottoman option perfectly align with the demand for versatile, Instagrammable home pieces. Additionally, TikTok Shop’s furniture boom and growing interest in hybrid leather/fabric sofas create a timely entry point.',
   'Young professionals aged 25-40, urban dwellers with $50K+ annual income, valuing minimalist Japandi and cozy home aesthetics, active on social media and seeking statement yet comfortable furniture for apartments or small homes.',
   '["shopify", "tiktok_shop", "amazon", "etsy", "wayfair"]',
   '["Negotiate with KABEQ for best FOB pricing and explore 3PL/freight forwarder options to reduce shipping costs.", "Run targeted TikTok and Instagram ads showcasing the sofa\\u2019s marshmallow texture and Japandi style to validate consumer interest.", "Leverage influencer partnerships and user-generated content to build brand trust and highlight lifestyle fit.", "Expand product line with complementary Japandi/cozy furniture pieces and optimize listings on Wayfair and Amazon for scale."]',
   'High shipping costs and potential delays could impact customer satisfaction; competition from established furniture brands with stronger logistics networks.',
   '45-65%',
   '$699-$1299',
   '["Japandi sofa", "cozy marshmallow sofa", "modular ottoman sofa", "soft leather fabric sofa", "minimalist living room furniture"]',
   '["Japandi", "cozy", "modular", "soft texture"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (211, 'furniture',
   72, 65, 60,
   55, 70,
   'Affordable Modern Leather Sofa Hits Sweet Spot for Young Buyers',
   'In 2025-2026, young professionals seek stylish yet affordable leather sofas that elevate their living spaces without breaking the bank. The Brown Sugar Sofa offers a clean modern aesthetic aligned with current minimalistic trends, making it highly relevant now. Additionally, the rise of TikTok Shop and other DTC channels enables effective direct-to-consumer marketing for mid-priced furniture.',
   'Urban professionals aged 25-40, mid to upper-middle income ($50k-$90k), design-conscious renters or first-time homeowners who value modern, affordable leather furniture with a premium look but accessible price.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Negotiate shipping and 3PL logistics to optimize freight costs and delivery times", "Run targeted ads on TikTok and Instagram to validate demand with young urban buyers", "Leverage influencer partnerships to showcase the sofa\\u2019s modern aesthetic and affordability", "Expand product line with complementary pieces and bundle offers to increase AOV and repeat purchases"]',
   'High shipping costs and potential damage during transit could impact margins and customer satisfaction; competition from established leather sofa brands remains moderate.',
   '45-60%',
   '$1799-$2299',
   '["affordable leather sofa", "modern sofa", "urban living room furniture", "young professional furniture", "clean design sofa"]',
   '["leather", "modern", "affordable", "bestseller"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (212, 'furniture',
   78, 85, 60,
   70, 75,
   'Tap into the booming premium cloud sofa trend for young urban buyers!',
   'The Cloud Sofa ZY aligns perfectly with the 2025 surge in demand for aesthetic, multi-material furniture among young professionals in the US and EU. With cloud and Japandi styles dominating, offering a premium leather option differentiates it in a crowded market. Dropshipping this sofa now leverages TikTok Shop’s furniture boom and growing consumer preference for statement, comfortable living room pieces.',
   'Urban professionals aged 25-40, mid to high income ($50k-$120k/year), design-conscious, value premium aesthetics and comfort, often first-time home buyers or renters upgrading living spaces, active on social media platforms like TikTok and Instagram.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Negotiate with KABEQ for sample units and shipping terms using freight forwarders to optimize costs.", "Validate market interest via targeted TikTok ads and Shopify pre-launch landing pages focusing on cloud and Japandi style keywords.", "Leverage influencer partnerships and TikTok Shop live streams showcasing the sofa\\u2019s premium materials and comfort.", "Scale by expanding to Amazon and Wayfair with optimized listings and bundling with complementary home decor items."]',
   'High shipping costs and potential delays could impact customer satisfaction; competition from established furniture brands with local warehouses may limit pricing power.',
   '45-60%',
   '$1,999 - $3,499',
   '["cloud sofa", "premium leather sofa", "Japandi furniture", "modern living room sofa", "multi-material sofa"]',
   '["cloud", "premium", "multi-material", "modern", "dropshipping"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (213, 'furniture',
   72, 78, 60,
   65, 70,
   'Curved Moon Sofa taps into cozy, aesthetic furniture trend for young buyers',
   'Curved and cozy furniture styles are surging in popularity among young US/EU consumers seeking unique, Instagrammable home pieces. The Moon Sofa’s moon-inspired design aligns with the growing curved furniture trend, while the MOQ of 1 piece enables flexible dropshipping. With TikTok Shop booming for furniture in 2025, now is the perfect time to introduce this high-end aesthetic piece.',
   'Young professionals aged 25-40, urban dwellers with $50k+ annual income, design-conscious, seeking cozy yet statement furniture to elevate their living spaces and share on social media.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Contact KABEQ to negotiate dropshipping terms and confirm shipping logistics with 3PL/freight forwarders", "Run targeted ads on TikTok and Instagram to validate demand and gather customer feedback", "Leverage influencer marketing focusing on home decor and aesthetic furniture niches", "Expand product line with complementary curved furniture and optimize logistics for faster delivery"]',
   'High shipping costs and potential delays could impact customer satisfaction; C-grade fabric may limit appeal to premium buyers seeking luxury materials.',
   '45-60%',
   '$2200-$3500',
   '["curved sofa", "moon sofa", "cozy fabric couch", "modern curved furniture", "aesthetic living room"]',
   '["curved", "fabric", "cozy", "moon", "modern"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (214, 'furniture',
   78, 85, 65,
   60, 75,
   'Capitalize on the Viral Japandi Togo-Style Lounge Chair for Gen Z & Millennials!',
   'The Caterpillar Lounge Chair taps into the booming Japandi and Togo-style furniture trends favored by young urban consumers seeking stylish yet comfortable floor seating. With TikTok Shop furniture sales surging in 2025 and low MOQ enabling fast testing, this product is primed for viral social media marketing and rapid dropshipping adoption.',
   'Young professionals and creatives aged 25-35, urban dwellers with $40k-$80k annual income, who prioritize minimalist Japandi aesthetics, social media trends, and multifunctional home comfort in small apartments.',
   '["shopify", "tiktok_shop", "amazon", "etsy", "wayfair"]',
   '["Secure a reliable freight forwarder or 3PL specializing in furniture to optimize shipping costs and delivery times.", "Launch a small test campaign on TikTok Shop using influencer partnerships to validate viral potential and price sensitivity.", "Create engaging content highlighting the Japandi aesthetic, comfort, and social proof from viral trends for TikTok and Instagram.", "Scale by expanding to Shopify and Wayfair with bundled offers including the ottoman, and optimize paid ads based on initial data."]',
   'High shipping costs and potential damage during transit could impact margins and customer satisfaction; competition from established Japandi and Togo-style chairs may intensify as trends mature.',
   '45-65%',
   '$499-$699',
   '["Japandi lounge chair", "Togo style chair", "floor lounge chair", "viral furniture 2025", "modern armchair"]',
   '["Japandi", "Togo-style", "floor chair", "viral", "lounge"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (215, 'furniture',
   72, 68, 55,
   75, 60,
   'Sculptural Crab Chair: A Bold Statement Piece for Trendy Millennials',
   'In 2025-2026, young urban consumers crave unique, designer furniture that doubles as art, making the Crab Chair\'s sculptural form highly appealing. With TikTok Shop booming for home decor, this eye-catching piece can leverage social media virality to drive sales. The limited competition for such distinctive armchairs also opens a niche window for early movers.',
   'Affluent millennials and Gen Z (age 25-40), earning $60K+, urban professionals and creatives who prioritize unique, Instagrammable home decor and invest in statement furniture pieces to reflect their lifestyle and aesthetic values.',
   '["shopify", "tiktok_shop", "etsy", "wayfair"]',
   '["Source a sample unit from KABEQ to evaluate quality and shipping logistics.", "Test market demand via targeted TikTok Shop ads and influencer partnerships focusing on design and lifestyle niches.", "Create visually rich social media campaigns emphasizing the chair\\u2019s sculptural, crab-inspired design and its status as a statement piece.", "Expand to Wayfair and Etsy for broader reach, optimize SEO with niche keywords, and negotiate better freight rates with 3PL providers to improve margins."]',
   'High shipping costs and potential damage during transit could reduce margins; niche style may limit mass-market appeal, requiring precise targeting and strong branding.',
   '40-60%',
   '$899-$1,199',
   '["designer armchair", "sculptural chair", "unique furniture", "statement chair", "crab chair"]',
   '["designer", "sculptural", "statement", "unique"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (216, 'furniture',
   78, 85, 65,
   70, 75,
   'Cozy Japandi Hippo Chair: Perfect Cute Armchair for Trendy Young Homes',
   'The Japandi and cozy boucle fabric trends are surging among young US/EU consumers seeking aesthetic, functional furniture for small spaces. With TikTok Shop booming for furniture and a growing appetite for unique, Instagrammable pieces, this adorable Hippo Chair fits perfectly into 2025-2026 style demands. Its single-piece MOQ and high-end look make it ideal for dropshipping with targeted marketing.',
   'Urban professionals aged 25-40, mid to upper-middle income ($50k-$90k), design-conscious millennials and Gen Z renters/homeowners who prioritize cozy, Instagrammable interiors and Japandi-inspired minimalist aesthetics.',
   '["shopify", "tiktok_shop", "amazon", "etsy", "wayfair"]',
   '["Order a sample unit to assess quality, comfort, and shipping logistics", "Run targeted TikTok and Instagram ads focusing on Japandi and cozy reading nook setups", "Leverage influencer partnerships and user-generated content to build social proof", "Expand product line with complementary cozy furniture and bundle offers to increase AOV"]',
   'High shipping costs and potential damage during transit could affect margins and customer satisfaction; niche style may limit mass appeal outside trend-focused buyers.',
   '45-65%',
   '$499-$599',
   '["Japandi armchair", "boucle chair", "cozy reading chair", "cute round chair", "modern cozy furniture"]',
   '["Japandi", "boucle", "cozy", "cute", "armchair"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (217, 'furniture',
   78, 70, 65,
   60, 75,
   'Cozy Oversized \'Mother\'s Embrace\' Chair Taps Nursery & Gift Market',
   'In 2025-2026, young urban parents and gifting buyers increasingly seek unique, cozy, and aesthetically pleasing furniture pieces that double as statement and comfort items. The oversized cocoon design fits perfectly with the ongoing trend for immersive comfort and nurturing home environments, especially in nursery and living spaces. Leveraging TikTok Shop and Shopify can capture the rising demand for experiential furniture among millennials and Gen Z.',
   'Young urban parents aged 28-38, middle to upper-middle income ($60k-$120k), lifestyle focused on family comfort, home aesthetics, and gifting meaningful, cozy furniture pieces for nurseries or living rooms.',
   '["shopify", "tiktok_shop", "amazon", "etsy", "wayfair"]',
   '["Establish a reliable freight forwarding and 3PL partnership to optimize shipping costs and delivery times.", "Run targeted TikTok Shop campaigns focusing on young parents and gift buyers to validate demand and messaging.", "Leverage influencer marketing around nursery and cozy home aesthetics, emphasizing the chair\\u2019s unique oversized cocoon design.", "Expand to Wayfair and Amazon with optimized listings and bundle offers, then scale paid ads and retargeting based on initial sales data."]',
   'High shipping costs and potential damage during transit could impact margins and customer satisfaction; niche style may limit mass appeal outside target demographics.',
   '45-60%',
   '$899-$1,199',
   '["oversized armchair", "cozy nursery chair", "cocoon chair", "unique armchair", "gift furniture"]',
   '["oversized", "cozy", "nursery", "unique", "giftable"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (218, 'furniture',
   68, 55, 60,
   70, 50,
   'Cute Polar Bear Ottoman: Playful Kids’ Room Must-Have in 2025!',
   'Novelty and playful furniture pieces for kids’ rooms are gaining traction as young parents seek unique, Instagrammable decor. With TikTok Shop booming and a rising interest in gifting and aesthetic children’s furniture, this polar bear ottoman fits a niche that blends fun and function. Its low MOQ and distinctive design make it a timely addition for dropshippers targeting young families.',
   'Young parents aged 28-38, middle to upper-middle income ($50k-$90k), urban or suburban lifestyle, value playful and Instagram-worthy home decor for kids’ rooms, often shopping online and influenced by social media trends.',
   '["shopify", "tiktok_shop", "amazon", "etsy", "wayfair"]',
   '["Contact supplier to confirm shipping options and 3PL partnerships for US/EU fulfillment.", "Run small-scale TikTok and Instagram ads targeting young parents to validate demand.", "Leverage influencer marketing focusing on family and home decor niches emphasizing novelty and cuteness.", "Expand product line with complementary kids\\u2019 furniture and bundle offers to increase average order value."]',
   'High shipping costs and potential damage during transit could affect margins; novelty appeal may limit broad market demand beyond niche buyers.',
   '40-60%',
   '$299-$399',
   '["kids ottoman", "polar bear furniture", "novelty ottoman", "children room decor", "cute kids furniture"]',
   '["novelty", "kids", "ottoman", "gift", "playful"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (219, 'furniture',
   72, 65, 55,
   70, 60,
   'Bold Red Loveseat: Perfect Romantic Statement for Young Homeowners',
   'In 2025-2026, young urban buyers are seeking unique, bold furniture pieces that double as statement décor, especially around gifting occasions like Valentine\'s Day and anniversaries. The Embrace Loveseat’s vibrant red fabric and romantic appeal tap into this niche, offering differentiation from the prevalent neutral-toned furniture market.',
   'Young professionals aged 28-38, mid to upper-middle income ($50k-$90k), urban dwellers with a passion for interior design, social media savvy, and looking for standout pieces to personalize small to medium-sized living spaces.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Set up a Shopify store integrated with TikTok Shop to leverage viral video marketing.", "Run targeted ads and influencer collaborations around Valentine\\u2019s Day and anniversary gifting seasons to validate demand.", "Create engaging content highlighting the loveseat\\u2019s bold color and romantic vibe, emphasizing lifestyle and gifting use cases.", "Expand into Wayfair and Amazon with optimized listings and bundle offers to scale sales post-validation."]',
   'High shipping costs and potential damage during transit could impact margins and customer satisfaction; niche color choice may limit broad appeal.',
   '45-60%',
   '$899-$1099',
   '["red loveseat", "romantic sofa", "bold furniture", "Valentine\'s gift sofa", "statement loveseat"]',
   '["loveseat", "bold color", "romantic", "fabric sofa"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (220, 'furniture',
   72, 68, 60,
   55, 70,
   'Modern Leather Dining Chair Perfect for Stylish Young Homes in 2025',
   'The demand for sleek, leather dining chairs with modern aesthetics is growing among young professionals furnishing their first homes or upgrading interiors. With TikTok Shop booming and consumers seeking premium yet affordable dining sets, this product fits the rising trend of minimalist, high-end furniture at accessible prices.',
   'Urban professionals aged 25-40, mid to upper-middle income ($50k-$100k), style-conscious, value modern design and quality materials, often living in apartments or new homes in US/EU metro areas.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Negotiate MOQ and shipping terms with KABEQ, explore 3PL/freight forwarders for cost-effective delivery", "Test market demand via TikTok Shop and Shopify with targeted ads focusing on modern leather dining sets", "Leverage influencer marketing and lifestyle content showcasing the chair in Japandi and modern interiors", "Scale by bundling chairs into sets and expanding to Wayfair and Amazon with optimized listings and reviews"]',
   'High shipping costs and potential damage during transit; competition from established brands offering similar modern leather chairs; fluctuating leather material prices may impact margins.',
   '45-60%',
   '$399-$499',
   '["modern dining chair", "leather dining chair", "sleek dining chair", "urban furniture", "young professional furniture"]',
   '["dining", "leather", "modern", "set"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (221, 'furniture',
   72, 65, 70,
   55, 68,
   'Ultra-affordable minimalist dining chair taps into young buyers’ style needs',
   'In 2025-2026, minimalist and affordable furniture is highly sought after by young urban professionals furnishing first homes or apartments. The rise of TikTok Shop and direct-to-consumer channels creates a prime environment to introduce volume-driven, budget-friendly dining chairs with a clean aesthetic. This product fits well into the growing demand for functional yet stylish pieces without premium pricing.',
   'Young professionals aged 25-35, middle income ($40K-$70K/year), urban dwellers who prioritize minimalist, affordable home decor and frequently shop online via social media platforms for trendy, budget-conscious furniture.',
   '["shopify", "tiktok_shop", "amazon", "etsy", "wayfair"]',
   '["Source initial MOQ batch and test shipping logistics with 3PL/freight forwarder to optimize costs", "Run targeted TikTok Shop and Instagram ads focusing on minimalist lifestyle and affordability", "Leverage influencer partnerships and user-generated content to build social proof and demand", "Expand product line with complementary minimalist dining furniture and scale via Wayfair and Amazon marketplaces"]',
   'High shipping costs and potential damage during transit can impact margins; competition from established budget furniture brands may limit pricing flexibility.',
   '45-60%',
   '$149-$199',
   '["minimalist dining chair", "affordable furniture", "tech fabric chair", "young professional decor", "budget dining chair"]',
   '["affordable", "minimalist", "dining", "volume"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (222, 'furniture',
   78, 85, 65,
   60, 75,
   'Affordable Sintered Stone Dining Tables Perfect for Modern Young Homes',
   'Sintered stone is rapidly gaining traction as a premium, durable surface material in the US/EU markets, especially among young urban buyers seeking modern industrial aesthetics. With TikTok Shop booming for furniture and growing demand for affordable yet high-end materials, this product hits a sweet spot in 2025-2026. The low MOQ and competitive factory pricing enable flexible dropshipping with good margins.',
   'Young professionals aged 25-40, urban dwellers with $50k-$90k annual income, design-conscious, value durability and modern industrial aesthetics, often first-time homeowners or renters upgrading dining spaces.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Set up a Shopify store with high-quality lifestyle and product imagery emphasizing the sintered stone top and industrial frame.", "Run targeted TikTok Shop ads focusing on modern apartment dwellers and young couples seeking affordable luxury dining furniture.", "Leverage influencer partnerships and user-generated content to showcase durability and style in real home settings.", "Expand to Amazon and Wayfair with optimized listings and explore 3PL partnerships to reduce shipping costs and delivery times."]',
   'High shipping costs and potential damage during transit can affect customer satisfaction; competition from established furniture brands offering similar materials may increase.',
   '45-65%',
   '$499-$699',
   '["sintered stone dining table", "modern industrial dining table", "affordable luxury furniture", "carbon steel frame table", "durable dining table"]',
   '["sintered stone", "modern", "dining", "affordable", "industrial"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (223, 'furniture',
   78, 85, 60,
   70, 75,
   'Premium Round Sintered Stone Dining Table Hits Luxury Aesthetic Trend',
   'Sintered stone furniture is rapidly gaining traction in the US/EU premium market due to its durability and modern luxury appeal. Young professionals aged 25-40 are actively seeking unique, high-end dining pieces that combine aesthetics with functionality, making this an ideal time to introduce a round sintered stone table. TikTok Shop’s rise as a furniture sales channel further amplifies this opportunity.',
   'Affluent urban professionals aged 28-38, income $70K+, design-conscious, value premium materials and unique luxury aesthetics, often living in modern apartments or homes with a focus on social dining experiences.',
   '["shopify", "tiktok_shop", "amazon", "wayfair"]',
   '["Source product samples and confirm quality with KABEQ factory to ensure premium finish.", "Validate demand via targeted social ads on TikTok and Instagram focusing on luxury dining aesthetics.", "Launch a branded Shopify store with influencer partnerships showcasing lifestyle use and durability.", "Scale by expanding to Wayfair and Amazon with optimized listings and leveraging 3PL for cost-effective shipping."]',
   'High shipping costs and potential damage during transit could impact margins and customer satisfaction; premium price point limits volume sales to niche buyers.',
   '45-60%',
   '$1200-$1800',
   '["sintered stone dining table", "round marble table", "luxury dining furniture", "premium dining table", "modern dining table"]',
   '["round", "marble", "sintered stone", "premium", "luxury"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (224, 'furniture',
   78, 85, 60,
   65, 75,
   'Japandi Stone-Top Dining Tables: The Must-Have Aesthetic for 2025-26',
   'The Japandi style, combining minimalism and natural materials, is rapidly gaining traction among young US/EU consumers seeking premium yet organic home decor. Sintered stone tops are emerging as a luxury alternative to marble, offering durability and a sleek look that aligns perfectly with 2025-26 design trends. With low MOQ and a factory price range that supports healthy margins, this product is primed for dropshipping success.',
   'Urban professionals aged 28-38, $60K+ annual income, design-conscious millennials and Gen Z who prioritize sustainable, natural, and trendy home aesthetics, often first-time homebuyers or renters investing in statement furniture pieces.',
   '["shopify", "tiktok_shop", "amazon", "etsy", "wayfair"]',
   '["Negotiate with KABEQ for sample orders and 3PL freight options to optimize shipping costs.", "Validate demand via targeted TikTok Shop ads focusing on Japandi and stone-top dining tables.", "Leverage influencer partnerships and lifestyle content highlighting the natural, premium look and durability.", "Scale by expanding SKUs (sizes/colors), bundling with complementary Japandi decor, and optimizing Amazon and Wayfair listings."]',
   'High shipping costs and potential damage during transit could impact margins and customer satisfaction; competition from established furniture brands may intensify as the trend grows.',
   '45-65%',
   '$899-$1,499',
   '["Japandi dining table", "stone top table", "sintered stone furniture", "natural wood dining table", "modern minimalist table"]',
   '["Japandi", "stone top", "wood base", "natural", "trending"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (225, 'furniture',
   78, 70, 65,
   60, 72,
   'Modern Sintered Stone Coffee Table: Trendy, Durable & Affordable!',
   'Sintered stone furniture is gaining traction in the US/EU as consumers seek durable, premium-feeling surfaces with modern industrial aesthetics. The rise of TikTok Shop and growing interest in unique materials like sintered stone make this an ideal time to introduce this coffee table to young urban buyers. Competitive pricing and low MOQ support agile dropshipping entry.',
   'Urban professionals aged 25-40, mid to upper-middle income ($50k-$90k), design-conscious millennials and Gen Z who prioritize modern, durable, and Instagram-worthy home decor with a preference for industrial and minimalist styles.',
   '["shopify", "tiktok_shop", "amazon", "etsy", "wayfair"]',
   '["Set up a Shopify store with strong visual storytelling emphasizing sintered stone benefits and modern design.", "Run targeted TikTok Shop campaigns focusing on young urban buyers showcasing the table\\u2019s durability and style in real home settings.", "Leverage influencer partnerships and user-generated content to build social proof and highlight the product\\u2019s premium look at an affordable price.", "Expand to Amazon and Wayfair with optimized listings and consider bundling with complementary decor items to increase average order value."]',
   'High shipping costs and potential damage during transit could impact margins and customer satisfaction; requires reliable 3PL and careful packaging. Moderate competition from established furniture brands using similar materials.',
   '45-60%',
   '$499-$699',
   '["sintered stone coffee table", "modern industrial furniture", "durable coffee table", "affordable designer table", "carbon steel base table"]',
   '["sintered stone", "modern", "coffee table", "industrial", "affordable"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (226, 'furniture',
   72, 65, 55,
   70, 60,
   'Luxury Glass & Marble Coffee Table Perfect for Stylish Living Rooms',
   'In 2025-2026, premium natural materials like Han Bai Yu marble combined with glass appeal to young professionals seeking statement furniture pieces. The rise of TikTok Shop and niche DTC brands targeting aesthetic-conscious buyers creates a timely window to introduce luxury coffee tables with authentic natural stone. Limited direct competition on mainstream platforms further enhances the opportunity.',
   'Affluent urban professionals aged 28-38, income $70K+, design-savvy, valuing luxury and natural materials, living in modern apartments or homes, interested in premium home decor and statement furniture pieces.',
   '["shopify", "tiktok_shop", "amazon", "etsy", "wayfair"]',
   '["Establish a partnership with KABEQ and arrange 3PL/freight forwarding for cost-effective shipping.", "Run targeted TikTok Shop and Instagram ads focusing on luxury and natural stone aesthetics to validate demand.", "Leverage influencer marketing and lifestyle content showcasing the table in premium living room setups.", "Expand product line with complementary marble/glass furniture and optimize listings on Wayfair and Amazon for broader reach."]',
   'High shipping costs and fragile materials increase logistics complexity; premium price point may limit mass-market appeal. Also, natural stone variations can affect product consistency.',
   '45-60%',
   '$999-$1,299',
   '["marble coffee table", "glass coffee table", "luxury furniture", "natural stone table", "modern living room"]',
   '["marble", "glass", "luxury", "premium", "natural stone"]',
   '2026-03-KABEQ', 1, NOW(), NOW()),
  (227, 'furniture',
   78, 82, 65,
   70, 75,
   'Affordable Japandi Round Side Tables Perfect for Trendy Young Homes',
   'The Japandi style continues to surge in popularity among young urban professionals seeking minimalist yet warm aesthetics. Sintered stone tops offer a premium look at a more accessible price point, meeting demand for durable, stylish furniture. With TikTok Shop and Shopify booming for home decor, this product fits perfectly into current consumer trends in 2025-2026.',
   'Urban professionals aged 25-40, mid to upper-middle income ($50k-$100k), design-conscious renters or first-time homeowners who prioritize affordable, versatile, and trendy furniture with a minimalist Japandi aesthetic.',
   '["shopify", "tiktok_shop", "amazon", "etsy", "wayfair"]',
   '["Negotiate with KABEQ for best FOB pricing and sample order to test quality and shipping logistics", "Validate demand via targeted TikTok Shop campaigns and Shopify pre-launch landing pages", "Leverage influencer partnerships and TikTok content showcasing Japandi styling and durability", "Scale by expanding SKUs (size variants), bundling with complementary Japandi decor, and optimizing 3PL freight forwarding"]',
   'High shipping costs and potential damage during transit could impact margins; competition from established furniture brands and local manufacturers may limit pricing power.',
   '45-65%',
   '$299-$499',
   '["Japandi side table", "sintered stone coffee table", "round side table", "affordable designer furniture", "minimalist home decor"]',
   '["Japandi", "round table", "sintered stone", "affordable", "versatile"]',
   '2026-03-KABEQ', 1, NOW(), NOW());

-- ── Done! ───────────────────────────────────────────────────────────────────
SELECT CONCAT('Inserted ', COUNT(*), ' KABEQ products into opportunity radar') as result
FROM product_opportunity_analysis WHERE batchId = '2026-03-KABEQ';